version: '3.8'

services:
    nodejs-app:
        build:
          context: ./task3/task2/myapp
        networks:
            - helloworld_bridge  
    nginx:
        build:
          context: ./task3/nginx
        ports:
            - "8000:80" 
        depends_on:
            - nodejs-app 
        networks:
            - helloworld_bridge

networks: 
  helloworld_bridge:
    external: true